#!/bin/bash
export B4RTOOLS_PATH=/home/tescam/b4r/qlook
export B4RDATA_PATH=/home/tescam/b4r/log
export B4RDATA_RSYNC_LOC=/home/tescam/b4r/bin/data_transfer_b4r1_teslx6.sh

# need to change
/home/tescam/.local/share/virtualenvs/qlook-v-9D3YAf/bin/python3.6 /home/tescam/b4r/qlook/b4rtools.py
